modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="moostensuraaddon"
version="1.4.0-rc1"
displayName="Moos Tensura Addon"

description='''
An unofficial companion addon for Tensura: Reincarnated that brings multiplayer-style progression into a meaningful singleplayer journey. Live out your incarnation through Soul Recognition, discover Great Crystal Shrines, awaken Sage into Great Sage, master the Unique Skill Granter, and evolve your authority into Benevolent Empowerment or Absolute Governance.
'''

[[dependencies.moostensuraaddon]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "tensura"
type = "required"
versionRange = "[2.0.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "manascore"
type = "required"
versionRange = "[4.0.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "manascore_skill"
type = "required"
versionRange = "[4.0.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "manascore_storage"
type = "required"
versionRange = "[4.0.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "manascore_network"
type = "required"
versionRange = "[4.0.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "geckolib"
type = "required"
versionRange = "[4.9.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moostensuraaddon]]
modId = "smartbrainlib"
type = "required"
versionRange = "[1.16.11,)"
ordering = "AFTER"
side = "BOTH"
